In [19]:
import pandas as pd
from datetime import time, datetime
import time as t


class selec_cor:
    OK = '\033[92m' #VERDE
    WARNING = '\033[93m' #AMARELO
    FAIL = '\033[91m' #VERMELHO
    RESET = '\033[0m' #RESETAR CORES
    REVERSE = "\033[;7m" #COR REVERSA
    DETAIL = "\033[1;34m" #AZUL
    BOLD = "\033[;1m" #NEGRITO



def transformar_dia(diadasemana):
    '''Esta função é para transformar o dia que seria
     trazido como número,para um dia da semana.
    Está relacionado com o dicionário localizado
     abaixo, o qual indica os dias correspondentes'''
    for l, each in enumerate(dicionario_dias) :
        if each == diadasemana:
            resultado = dicionario_dias[l]
            return resultado
        else:
            pass


def adaptar_item(item):
    '''Adapta o item que for menor que 10 para pôr um 0 na frente '''
    if item < 10:
        item = '0' + str(item)
        return item
    else:
        return item


def verificar_aprovacao():
    '''Verifica a aprovação do aluno; podendo ter 3 opções de aprovação. 
    Uma, caso passe com a média maior ou igual à 95,
     outra caso passe mas seja menor que 95 e outra caso não passe'''
    if  media_final >= meta_media:
        
        if media_final >= reqde_certify:
            return f'|{nome_aluno:^30}|{curso:^25}|Qtde Aulas:{qnt_aula:^5}|' + f'\033[44m{media_final:^10.2f}\033[0m|'.replace('.',',')

        return f'|{nome_aluno:^30}|{curso:^25}|Qtde Aulas:{qnt_aula:^5}|' + f'\033[42m{media_final:^10.2f}\033[0m|'.replace('.',',')
        
    else:
        return f'|{nome_aluno:^30}|{curso:^25}|Qtde Aulas:{qnt_aula:^5}|' + f'\033[41m{media_final:^10.2f}\033[0m|'.replace('.',',')



dicionario_dias = { 
0: 'Segunda-feira',
1: 'Terça-feira',
2: 'Quarta-feira',
3: 'Quinta-feira',
4: 'Sexta-feira',
5: 'Sábado',
6: 'Domingo',
}



data_atual = t.localtime()
ano, mes, dia, hora, minuto, segundo, diadasemana, diadoano, isdst = data_atual
hoje = f'{adaptar_item(dia)}/{adaptar_item(mes)}/{ano}'

reqde_certify = 95
meta_media = 70

while True:

    nome_aluno = input('Informe o nome do aluno: \n').strip().title()
    if nome_aluno == '':
        print( selec_cor.FAIL + 'Error N!' + selec_cor.RESET + '\nO dado inserido não é válido. Favor, preencher corretamente.')
        break

    else:
        pass

 
    curso = input('Qual o curso do aluno {} está querendo saber a média? \n'
    .format(nome_aluno)).strip().title()


    if curso == '':
        print( selec_cor.FAIL + 'Error C!' + selec_cor.RESET + '\nO dado inserido não é válido. Favor, preencher corretamente.')
        break
    
    elif len(curso) <= 3:
        curso = curso.upper()

    else:
        pass


    #quantidade de aulas do curso inserido anteriormente 
    qnt_aula = int(input('Insira a quantidade de aulas que o curso de {} tem: \n'.format(curso)).strip())
    if qnt_aula <= 36: #36 é a maior quantidade de aula de um único curso para onde formulei este algoritmo 
        pass

    else:
        print( selec_cor.FAIL + 'Error Q!' + selec_cor.RESET + '\nO dado inserido não é válido. Favor, preencher corretamente.')
        break


    if nome_aluno and curso and qnt_aula:
    
        contadorwhile = 0
        soma = 0
        while contadorwhile < int(qnt_aula):

            soma += float(input('Insira a nota que o aluno(a) {a} tirou correspondente à AULA {c}.\n(Total de aulas restantes a serem preenchidas: {q})\n'
            .format(q = int(qnt_aula) - contadorwhile, c = contadorwhile + 1, a = nome_aluno)))
            contadorwhile += 1

        media_final = soma / int(qnt_aula)

        print(verificar_aprovacao())
        print('=' * 85)
    
        data_conclusao =f'{hoje}, {adaptar_item(hora)}h{adaptar_item(minuto)}min.'
        texto = f"Pesquisa realizada em {transformar_dia(diadasemana)}, {data_conclusao}"
        print('\033[44m{:^85}\033[0m'.format(texto))
    break

|        Lucas Lourenco        |         Inglês          |Qtde Aulas:  3  |  100,00  |
=====================================================================================
              Pesquisa realizada em Terça-feira, 20/09/2022, 21h14min.

In [24]:
dados = {
         'Nome':nome_aluno,
         'Curso':curso, 
         'Média':media_final, 
         'Qntd Aulas':qnt_aula,
         'Data de Conclusão':data_conclusao
        }



alunos_concluidos_df = pd.read_excel('Média de Alunos Concluidos.xlsx')
alunos_concluidos_df = alunos_concluidos_df[['Nome','Curso','Média','Qntd Aulas','Data de Conclusão']]
display(alunos_concluidos_df)

pergunta = input('Deseja adicionar este aluno à planilha de excel?').lower()
if pergunta in ['sim','s','desejo']:
    
    try:
        alunos_concluidos_df.loc[len(alunos_concluidos_df) + 1] = dados
        alunos_concluidos_df.to_excel('Média de Alunos Concluidos.xlsx', encoding='latin')
        print('Alocado à planilha.','\n'*2)
        
    except:
        print('NÃO foi possível alocar à planilha.')
    
    finally:
        texto=['Programa Encerrado.','Resultado da planilha:']
        print('\n'.join(texto))
        
        display(alunos_concluidos_df)
    
    
else:
    print('não adicionado à planilha de excel')

             Nome     Curso  Média  Qntd Aulas      Data de Conclusão
0  Lucas Lourenco    Python    100           2  20/09/2022, 20h54min.
1   Fulano De Tal  Power Bi    100           2  20/09/2022, 21h00min.
2  Lucas Lourenco       SQL    100           2  20/09/2022, 21h00min.
3  Lucas Lourenco       SQL    100           2  20/09/2022, 21h00min.
4   Fulano De Tal     Excel    100           2  20/09/2022, 21h12min.

Alocado à planilha.


Programa Encerrado.
Resultado da planilha:

             Nome     Curso  Média  Qntd Aulas      Data de Conclusão
0  Lucas Lourenco    Python  100.0           2  20/09/2022, 20h54min.
1   Fulano De Tal  Power Bi  100.0           2  20/09/2022, 21h00min.
2  Lucas Lourenco       SQL  100.0           2  20/09/2022, 21h00min.
3  Lucas Lourenco       SQL  100.0           2  20/09/2022, 21h00min.
4   Fulano De Tal     Excel  100.0           2  20/09/2022, 21h12min.
6  Lucas Lourenco    Inglês  100.0           3  20/09/2022, 21h14min.

In [ ]:
#caso esteja rodando pela primeira vez, use este código aqui:
########### ATENÇÃO, SOMENTE CASO TENHA RODADO PELA PRIMEIRA VEZ, APÓS ELA, APAGUE O CÓDIGO OU COMENTE-O
# (pode rodar aqui mesmo, só tirar as hashtags abaixo)



# dados = {
#          'Nome':nome_aluno,
#          'Curso':curso, 
#          'Média':media_final, 
#          'Qntd Aulas':qnt_aula,
#          'Data de Conclusão':data_conclusao
#         }

# alunos_concluidos_df = pd.DataFrame.from_dict(dados)

In [ ]:
########### para excluir linhas

# alunos_concluidos_df = alunos_concluidos_df.drop(5, axis=0)

# display(alunos_concluidos_df)
# alunos_concluidos_df.to_excel('Média de Alunos Concluidos.xlsx', encoding='latin')